### ISSUE TITLE
Trouble during Migration: Cannot read property 'describe' of undefined

### ISSUE THREAD

**Issue by georgiemathews** [mujz/pg-search-sequelize#1]
When I attempt to migrate using sequelize-cli, I get the following error:
Cannot read property 'describe' of undefined

My migration file is as follows:
```
const QueryInterface = require('pg-search-sequelize').QueryInterface;
const models = require('../src/data/models');
import Sequelize from 'sequelize'
// The model we're creating the materialized view for

const materializedViewName = 'source_materialized_view';
const attributes = { // field: weight. Every field has a weight to calculate how relevant the search results are.
  title: 'A', // name has the highest weight.
  category: 'B',
  url: 'D', // city has a lower weight than title and description
};

const options = {
  include: [ // You can also include fields from associated models
    {
      model: models.Tag,
      foreignKey: 'tag_id',
      targetKey: 'id',
      associationType: 'belongsToMany', // association types are: belongsTo, hasOne, or hasMany
      attributes: { // Those attributes get added to the materialized view's search document and will also be searched just like the other fields
        keywords: 'C',
      },
    },
  ],
};
module.exports = {
  up: queryInterface => new QueryInterface(queryInterface).createMaterializedView(materializedViewName, models.Source, attributes, options),

  down: queryInterface => new QueryInterface(queryInterface).dropMaterializedView(materializedViewName),
};
```

**Comment by mujz** [comment]
What's the relationship between the `Tag` and `Source` models?
Can you share your model definitions with me?
Also, can you post the full error message?
Thanks :)

**Comment by mujz** [comment]
I just pushed a fix. Please upgrade to version 0.0.10 and try again.
I do see one issue with your migration though. Valid association types are: belongsTo, hasOne, or hasMany. Please check the [documentation](https://github.com/mujz/pg-search-sequelize#creatematerializedviewname-model-attributes-options) for more information.
I'll close this issue for now since it seems to be fixed on my end. Please feel free to reopen it if you're still having problems.

**Comment by georgiemathews** [comment]
Thank you, sorry for the late response, I ended up changing my models to match the code example, and fixed the associations issue. Everything is working as of now, without the upgrade, but I will go ahead and upgrade. Thanks for the help!

**Comment by mujz** [comment]
Glad to hear that it worked :)
